config/routes.rb
Rails.application.routes.draw do
  resources :gitevents

  root 'welcome#index'

  post 'update', to: 'welcome#update_database'

end

app/models/gitevent.rb
class Gitevent
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  field :id, type: String
  field :type, type: String
  field :public, type: Mongoid::Boolean
  field :created_at, type: DateTime
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gitevents_controller.rb
class GiteventsController < ApplicationController
  before_action :set_gitevent, only: [:show, :edit, :update, :destroy]

  # GET /gitevents
  # GET /gitevents.json
  def index
    @gitevents = Gitevent.page params[:page]
  end

  # GET /gitevents/1
  # GET /gitevents/1.json
  def show
  end

  # GET /gitevents/new
  def new
    @gitevent = Gitevent.new
  end

  # GET /gitevents/1/edit
  def edit
  end

  # POST /gitevents
  # POST /gitevents.json
  def create
    @gitevent = Gitevent.new(gitevent_params)

    respond_to do |format|
      if @gitevent.save
        format.html { redirect_to @gitevent, notice: 'Gitevent was successfully created.' }
        format.json { render :show, status: :created, location: @gitevent }
      else
        format.html { render :new }
        format.json { render json: @gitevent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gitevents/1
  # PATCH/PUT /gitevents/1.json
  def update
    respond_to do |format|
      if @gitevent.update(gitevent_params)
        format.html { redirect_to @gitevent, notice: 'Gitevent was successfully updated.' }
        format.json { render :show, status: :ok, location: @gitevent }
      else
        format.html { render :edit }
        format.json { render json: @gitevent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gitevents/1
  # DELETE /gitevents/1.json
  def destroy
    @gitevent.destroy
    respond_to do |format|
      format.html { redirect_to gitevents_url, notice: 'Gitevent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gitevent
      @gitevent = Gitevent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gitevent_params
      params.require(:gitevent).permit(:id, :type, :public, :created_at)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def index
  	@gitevents_by_types = Array.new
    gitevents_types = Gitevent.distinct(:type)
  	gitevents_types.each do |type|
  		gitevent = {}
  		gitevent["type"] = type
  		gitevent["count"] = Gitevent.where(type: type).count
  		@gitevents_by_types.push(gitevent)
  	end

    map = %Q{
      function() {
        var date = new Date(this.created_at.getFullYear(),
                                         this.created_at.getMonth(),
                                         this.created_at.getDate(),
                                         this.created_at.getHours(),
                                         this.created_at.getMinutes());
        emit(date, {type: this.type, count: 1});
      }
    }

    reduce = %Q{
      function(key, values) {
        var total = {};
        for(var i = 0; i < values.length; i++) {
            if (!(values[i].type in total)) {
                total[values[i].type] = 0;
            }
            total[values[i].type] += values[i].count; 
        }
        return total;
      }
    }

    @gitevents_types_by_date = Gitevent.map_reduce(map, reduce).out(inline: true)

  end

  def update_database
    UpdateDatabase.perform_async(params[:year], params[:month], params[:day], params[:hour])
  end
end 

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gitevents_helper.rb
module GiteventsHelper
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gitevents/_form.html.erb
<%= form_for(@gitevent) do |f| %>
  <% if @gitevent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gitevent.errors.count, "error") %> prohibited this gitevent from being saved:</h2>

      <ul>
      <% @gitevent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :public %><br>
    <%= f.check_box :public %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br>
    <%= f.text_field :created_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gitevents/edit.html.erb
<h1>Editing Gitevent</h1>

<%= render 'form' %>

<%= link_to 'Show', @gitevent %> |
<%= link_to 'Back', gitevents_path %>

app/views/gitevents/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="page-header">Listing Gitevents</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Id</th>
      <th>Type</th>
      <th>Public</th>
      <th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gitevents.each do |gitevent| %>
      <tr>
        <td><%= gitevent.id %></td>
        <td><%= gitevent.type %></td>
        <td><%= gitevent.public %></td>
        <td><%= gitevent.created_at %></td>
        <td><%= link_to 'Show', gitevent %></td>
        <td><%= link_to 'Edit', edit_gitevent_path(gitevent) %></td>
        <td><%= link_to 'Destroy', gitevent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @gitevents %>

<br>

<%= link_to 'New Gitevent', new_gitevent_path, class: "btn btn-primary" %>

app/views/gitevents/new.html.erb
<h1>New Gitevent</h1>

<%= render 'form' %>

<%= link_to 'Back', gitevents_path %>

app/views/gitevents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @gitevent.id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @gitevent.type %>
</p>

<p>
  <strong>Public:</strong>
  <%= @gitevent.public %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @gitevent.created_at %>
</p>

<%= link_to 'Edit', edit_gitevent_path(@gitevent) %> |
<%= link_to 'Back', gitevents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KittyHub</title>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
	<body>	
		<nav class="navbar navbar-inverse navbar-fixed-top">
	      <div class="container-fluid">
	        <div class="navbar-header">
	          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	            <span class="sr-only">Toggle navigation</span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	          </button>
	          <a class="navbar-brand" href="/">Kitty Hub</a>
	        </div>
	        <div id="navbar" class="navbar-collapse collapse">
	          <ul class="nav navbar-nav navbar-right">
	            <li><a href="/">Dashboard</a></li>
	          </ul>
	          <form class="navbar-form navbar-right">
	            <input type="text" class="form-control" placeholder="Search...">
	          </form>
	        </div>
	      </div>
	    </nav>

	    <div class="container-fluid">
	      <div class="row">
	        <div class="col-sm-3 col-md-2 sidebar">
	          <ul class="nav nav-sidebar">
	            <li class="active"><a href="/">Overview <span class="sr-only">(current)</span></a></li>
	            <li><a href="/gitevents">List</a></li>
	          </ul>
	        </div>
	        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
				<%= yield %>
	        </div>
	      </div>
	    </div>
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.js"></script>
	    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
	</body>
</html>

app/views/welcome/index.html.erb
<h1 class="page-header">Dashboard</h1>

<div class="row">
	<div id="donut-by-type"></div>
</div>

<div class="row">
	<div id="chart-type-by-date"></div>
</div>

<div class="row">
	<form accept-charset="UTF-8" action="/update" method="post">
	  <input type="text" name="year" placeholder="year" />
	  <input type="text" name="month" placeholder="month" />
	  <input type="text" name="day" placeholder="day" />
	  <input type="text" name="hour" placeholder="hour" />
	  <input type="submit"/>
	</form>
</div>

<script type="text/javascript">
	<% if @gitevents_by_types %>
		Morris.Donut({
		  element: 'donut-by-type',
		  data: [
		  	<% @gitevents_by_types.each do |gitevent| %>
				{label: '<%= gitevent["type"] %>' , value: <%= gitevent["count"] %>},	
			<% end %>
		  ]
		});
	<% end %>

	<% if @gitevents_types_by_date %>
		Morris.Line({
		  element: 'chart-type-by-date',
		  data: [
		  	<% @gitevents_types_by_date.each do |gitevent| %>
				{created_at: '<%= gitevent["_id"].to_s(:db) %>' , 
					<% gitevent["value"].each do |type, count| %>
						<%= type %>: <%= count %>,
					<% end %>
				},	
			<% end %>
		  ],
		  xkey: 'created_at',
		  ykeys: [
		  	<% @gitevents_by_types.each do |gitevent| %>
				'<%= gitevent["type"] %>',	
			<% end %>
		  ],
		  labels: [
		  	<% @gitevents_by_types.each do |gitevent| %>
				'<%= gitevent["type"] %>',	
			<% end %>
		  ]
		});
	<% end %> 
</script>

app/views/welcome/update_database.erb
<h1 class="page-header">Dashboard</h1>

<p>La base de donnée est en cours de mise à jour.</p>